### ISSUE TITLE
Leaves on NT Trees Decay

### ISSUE THREAD

**Issue by Slayde4** [TheKiipster/Novam-Terram#9]
Leaves will decay in differing circumstances without their respective tree trunks being removed. Some decay while I'm walking around, others decay when a single leaf on the tree is broken, & more will decay if the leaves are used as regular blocks.

Sometimes this also affects vanilla leaves if a leaf of another kind is placed next to it, but the decay is usually slower.

I only have NT installed (though I have used other mods with it and the problem persists). I did most of my testing in creative mode, but when I used survival I've found that the leaves decay as well.

I'm currently using version 6.1 of the mod (which is otherwise great btw).

I can provide a list of the leaves I've found to decay if that helps you out.

**Comment by TheKiipster** [comment]
Yeah can you provide a list of leaves that decay that should help

**Comment by Slayde4** [comment]
Here's a list so far. I'll do some more testing when I can throughout the holiday.

### Walking Around

- Red Spruce Leaves on Red Spruce Trees
- Red Spruce Leaves on Mega Red Spruce Trees
- Blue Spruce Leaves on Blue Spruce Trees
- Blue Spruce Leaves on Mega Blue Spruce Trees

### If I Break 1 Tree Leaf

- These Pines

![nt pine 1](https://user-images.githubusercontent.com/46070580/50405576-ddd03c80-0784-11e9-86f9-547bfcfc6468.png)

- Red Autumn Leaves

### If I Place Other NT Leaves on the Tree

- These Pines

![nt pine 2](https://user-images.githubusercontent.com/46070580/50405573-d6a92e80-0784-11e9-8d55-fd69ea705bd3.png)

### Leaves Placed in Mid-Air

- Red Spruce Leaves
- Blue Spruce Leaves
- Maple Leaves
- Brown Autumn Leaves
- Orange Autumn Leaves
- Red Autumn Leaves
- Yellow Autumn Leaves

### Leaves Placed on the Ground

- Red Spruce Leaves
- Maple Leaves
- Brown Autumn Leaves
- Orange Autumn Leaves
- Red Autumn Leaves
- Yellow Autumn Leaves

### Leaves Placed on the Ground in a 3x3 pattern with the center leaf broken.

- Blue Spruce Leaves

**Comment by Slayde4** [comment]
I also forgot to mention this but I am using the latest recommended version of Forge (14.23.5.2768).

**Comment by Slayde4** [comment]
Here's the results of more testing.

**Planted Tree, Walking Around**

- Blue Spruce
- Red Spruce
- White (Also, the planted version of the tree is not the same as the wild version)

**If I Break 1 Leaf on the Tree**

- White Tree

**If I Place Other NT Leaves on the Tree**

- The Pine/Taller Spruce Trees in the Green Mixed Forest Biome
- Estuary Trees

**Placing Leaves on the Ground**

- Myrtle

**Placing Leaves on the Ground, then Breaking One**

- White

**Placing Leaves in Mid-Air**

- Myrtle
- White

**Trees Without any Problems**

- Poplar
- Any Shrubs with Vanilla Leaves
- Normal Sized Oak Trees
- Mega Spruces

**Comment by TheKiipster** [comment]
Alright so I went in a vanilla game increased the tick speed and broke leaves from vanilla trees and some of them also experienced this like the big oaks and spruce trees. I think I cant really fix this since its a vanilla problem, I think . Like the leaves are generated too far away from a log block so when the leaf block is broken is starts decaying. I dont know why some leaves decay while your just walking around that's really weird. Also I'm thinking of just getting rid of the tall spruce trees and just using normal spruce trees instead since their really isn't a big difference between the two, maybe even getting rid of the pine trees too since they end up causing too much lag and they dont even look that great.

**Comment by TheKiipster** [comment]
The Red & Blue Spruce Trees are also just variants of the "Taller Spruce Trees" so if I do get rid of the taller spruce trees they should start working properly since they'd be based off of a regular spruce tree

**Comment by Slayde4** [comment]
> I think I cant really fix this since its a vanilla problem, I think . Like the leaves are generated too far away from a log block so when the leaf block is broken is starts decaying

I checked the minecraft wiki and you're right. Any naturally generated leaf block has to be within four blocks of their respective log block.

**Comment by Slayde4** [comment]
> The Red & Blue Spruce Trees are also just variants of the "Taller Spruce Trees" so if I do get rid of the taller spruce trees they should start working properly since they'd be based off of a regular spruce tree

I never experienced any issues with the Spruce Tree models so it might be a good idea to give it a go.

**Comment by Slayde4** [comment]
That leaves the issues of placed leaves decaying and the random decaying of leaves.

I've also found that Paulownia Trees suffer from the random decaying as well while the Autumn and Maple Trees don't.

**Comment by TheKiipster** [comment]
Yeah the Paulownia Trees were a mess I was just messing around with things & that was the outcome, I wont remove the trees but ill most likely change them.

**Comment by Slayde4** [comment]
I checked all the unique trees I'm pretty sure, and there aren't any more leaves randomly decaying on trees.

Here are the rest of the leaves (sorry for the belated response).

**Leaves that Decay in Mid-Air**

Red Oak
Magenta Cherry
White Cherry
Pink Cherry
Jacaranda
Paulownia

**Leaves that decay once broken on the ground**

Red Oak
Magenta Cherry
White Cherry
Pink Cherry
Jacaranda
Paulownia

**Comment by Slayde4** [comment]
Checking in a few months later. Not sure what changed, but I don't think the trees are decaying like they used to (they seem normal).
